apiVersion: v1
kind: Pod
metadata:
  name: dns-observer
spec:
  containers:
  - name: dns-observer
    image: gcr.io/zihongz-kubernetes-codelab/dns-observer:0.2
    command: ["sh", "-c"]
    args: ["while true ; do sleep 3600 ; done"]
    imagePullPolicy: Always
  restartPolicy: Never
